### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by sg1970** [juergenschubert/DELLEMC-DPS-ReST-api#1]
Hello thanks for building this repo. Could you please provide some usage examples on how to use this so that i can get started. ( Iam new to the world of Dell EMC networker so feeling a bit lost.) Any help would be appreciated. thanks !

**Comment by juergenschubert** [comment]
This is all used with postman. here you can import the collection and the variables

**Comment by juergenschubert** [comment]
As we are trying to focus for Rest APi prototyping with Postman we have created collections and variables you can use with the products. All collections will not include 100% of the api but at lease some examples you are ready to use with
